version: '3.8'

services:
  backend:
    build:
      context: ./backend/flask
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./backend/flask:/src
    depends_on:
      - mongo

  mongo:
    image: mongo

  frontend:
    build:
      context: ./frontend/vuejs
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./frontend/vuejs:/project
      - /project/node_modules
    depends_on:
      - backend

  web:
    image: nginx
    volumes:
      - ./backend/nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
